"""sync_current_models_with_database

Revision ID: 7cfa2d9130ca
Revises: 05e3e980e152
Create Date: 2025-10-09 19:26:45.761976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cfa2d9130ca'
down_revision: Union[str, None] = '05e3e980e152'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ad_token_tenant', table_name='ad_token')
    op.drop_index('idx_automation_destination', table_name='automation')
    op.add_column('user', sa.Column('password_hash', sa.String(length=255), nullable=True))

    # Add email_verified column with default value first
    op.add_column('user', sa.Column('email_verified', sa.Boolean(), nullable=True, default=False))
    # Update all existing rows to have email_verified = False
    op.execute("UPDATE \"user\" SET email_verified = FALSE WHERE email_verified IS NULL")
    # Now make the column NOT NULL
    op.alter_column('user', 'email_verified', nullable=False)

    op.add_column('user', sa.Column('profile_data', sa.JSON(), nullable=True))
    op.drop_index('idx_user_tenant', table_name='user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_user_tenant', 'user', ['tenant_id'], unique=False)
    op.drop_column('user', 'profile_data')
    op.drop_column('user', 'email_verified')
    op.drop_column('user', 'password_hash')
    op.create_index('idx_automation_destination', 'automation', ['destination_id'], unique=False)
    op.create_index('idx_ad_token_tenant', 'ad_token', ['tenant_id'], unique=False)
    # ### end Alembic commands ###
